sudo: false
env:
  global:
  - IDE_VERSION=1.8.5
before_script:
- wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
- tar xf arduino-$IDE_VERSION-linux64.tar.xz
- mv arduino-$IDE_VERSION $HOME/arduino-ide
- export PATH=$PATH:$HOME/arduino-ide
- rm -rf arduino-$IDE_VERSION-linux64.tar.xz
script:
# Create archive and package_sensebox_index.json
- "./extras/pack.release.bash"
- "./extras/test.release.bash"
# Get the current version for deployment
- SENSEBOXCORE_VERSION=$(grep version= platform.txt | sed 's/version=//g')
# originall in in before_deploy, but this is ran before each deploy provider
# so just do it once here..
- mkdir -p deploy
- mv package_sensebox_index.json_original deploy/package_sensebox_index.json
deploy:
  - provider: releases
    file: "packages/arduino-senseBoxCore-${SENSEBOXCORE_VERSION}.tar.bz2"
    api_key:
      secure: fBQh1gog1+IR6GwXC0nKjIvku4Mtme5EpVhdkO+LXz8sCy0di76otDtS/YQ5Gviw35bMst0++vJsFYwlw3ViuEv9NEk9rQ5DWBFc40UazrkXi09MmkfwNm40FXOHNwioeX79GTwhqFqNdK8C248t3/jICqHcf0GOMa8yr07VpLAsSXYKVAI4aVE/4Pe6ZsQ0eTpSgw/uUyVP0RUI68WACvJkrXj29Z56tt58v7nUPe6VMp3zROH2iZpPhpYNm8FmwOb19Ax8fSU6ei7/wX+cnfw5gLGh0j8/re/j6fHr6eSYUBXzF84/DFKi4EVmpThqPBtdM+rL4raAk5tvUD3pQBiclJ32EYjJKEmi0foFL0ZqkItZV6VGvdJGVcSul9XrqAHq1YxoSAoyWicrbV9QQFhMP812LCjHEqsBYUt2xKP2JYDkSrJmFQFX0emOTFIzBD6jyjC3aTpxR6QjwUFsv4SLU5ag9gLVUem5o4C16wzbWfJiT4/6FrCjH1RhdfqtTZnOPktDFMNyxru40TyDIWZSJx9npkS6wcDBbLeCj+duVvWIO7C2lvenxb1TVcn8BuIm0Ing2Qvq26dYQJeYo8xmSzTcQUNHUvUbCzxpoJvS5Cj1EIZgmjPL9V1l3TPJAzVsHt0dAF4OW/XJpOYSEHnw8UgKsiZUDcrbVAK0fS0=
    skip_cleanup: true
    on:
      repo: sensebox/arduino-senseBoxCore
      branch: master
      tags: true
  # Deploy package_sensebox_index.json to Github pages
  - provider: pages
    github_token:
      secure: aPjPB1EqQqQt7UEzo/9Di35+hAl9ctfAoE8KCtEXsk0itUsN8DhSgJu1WX6xmo9r4xDayLCfxyVQepfU49d0McHRJYZCPN0pvHQMmWFs7/tzOB/MGGqxy5zkqdAx2Z52HrKQ9DjL8epHuImm8DzX60Nyyd6bTN7WDnZI/1lIWFvm7KxfLxyb3F76b/zjTln5QFNAnM52FIVNkSxjc0xEnNzabKEDXICQCrrb1nymqjbFx0tnbTcFWqVKu93VY31P91eNslB9dI1XDJGwUUH1ZaCNxUOFScD2mV7tHPl8XQWa3ew4P72CJDvdpvRa7Lx17ddLr5THtMxaxCUuXAsld+JZ1N60o4rTcxPmdNbp4lFp0isSkEgkfxyqRSaxQ4Ex8Vpp1fYPSfT4H4RDQUaKWzX21L89idynescT8sV1J/q0BQruDPM7cgbTr2WCP2w+claw74ZnHjdSr9awlNKS8S87OjeC4+nKBdrYoUaLKx+lwss1jcMqXY82x8zPIbEGWwFVqYmrLqYwJTUaHxCukCVBZZwt1deBeJjqnyqaGdzGZ25cGZAnAwZjBcXpdX226DuKBlD3fnwbxX9jguroNOqGYY3i/r+hJ6mo3IYcG/CgwOpVYWZKCLdYJEwki6TNSY8+7Op/txJwCl3nWqqVoX3qp7hC6NLPToHBAu0sgNM=
    local_dir: deploy
    skip_cleanup: true
    on:
      repo: sensebox/arduino-senseBoxCore
      branch: master
      tags: true
